export { default as Weather } from '../DashboardComponents/Weather'
export { default as TasksProgress } from './ForecastWeek'
export { default as TotalProfit } from '../DashboardComponents/TotalPrice'
export { default as Forecast } from '../DashboardComponents/Forecast'
export { default as Map } from './Map'
export { default as Table } from '../DashboardComponents/Table'
