export { default as Weather } from '../DashboardComponents/Weather'
export { default as TasksProgress } from '../DashboardComponents/TaskProgress'
export { default as TotalProfit } from '../DashboardComponents/TotalProfit'
export { default as Forecast } from '../DashboardComponents/Forecast'
export { default as Graph } from '../DashboardComponents/Graph'
